set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_CTS] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_RTS]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO00] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO00]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO09] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO09]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO14] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO14]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO15] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO15]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO16] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO16]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO17] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO17]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO18] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO18]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO19] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO19]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO22] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO22]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO23] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO23]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO24] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO24]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO25] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO25]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO26] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO26]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO27] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO27]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO28] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO28]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO29] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO29]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO30] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO30]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO31] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO31]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO32] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO32]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO33] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO33]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO34] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO34]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO37] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO37]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO44] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO44]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO48] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO48]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO53] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO53]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO54] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO54]