	CV96_QSYS u0 (
		.hps_0_h2f_user0_clock_clk      (<connected-to-hps_0_h2f_user0_clock_clk>),      // hps_0_h2f_user0_clock.clk
		.hps_0_h2f_user1_clock_clk      (<connected-to-hps_0_h2f_user1_clock_clk>),      // hps_0_h2f_user1_clock.clk
		.hps_io_hps_io_uart0_inst_RX    (<connected-to-hps_io_hps_io_uart0_inst_RX>),    //                hps_io.hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX    (<connected-to-hps_io_hps_io_uart0_inst_TX>),    //                      .hps_io_uart0_inst_TX
		.hps_io_hps_io_uart0_inst_CTS   (<connected-to-hps_io_hps_io_uart0_inst_CTS>),   //                      .hps_io_uart0_inst_CTS
		.hps_io_hps_io_uart0_inst_RTS   (<connected-to-hps_io_hps_io_uart0_inst_RTS>),   //                      .hps_io_uart0_inst_RTS
		.hps_io_hps_io_gpio_inst_GPIO00 (<connected-to-hps_io_hps_io_gpio_inst_GPIO00>), //                      .hps_io_gpio_inst_GPIO00
		.hps_io_hps_io_gpio_inst_GPIO09 (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>), //                      .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO14 (<connected-to-hps_io_hps_io_gpio_inst_GPIO14>), //                      .hps_io_gpio_inst_GPIO14
		.hps_io_hps_io_gpio_inst_GPIO15 (<connected-to-hps_io_hps_io_gpio_inst_GPIO15>), //                      .hps_io_gpio_inst_GPIO15
		.hps_io_hps_io_gpio_inst_GPIO16 (<connected-to-hps_io_hps_io_gpio_inst_GPIO16>), //                      .hps_io_gpio_inst_GPIO16
		.hps_io_hps_io_gpio_inst_GPIO17 (<connected-to-hps_io_hps_io_gpio_inst_GPIO17>), //                      .hps_io_gpio_inst_GPIO17
		.hps_io_hps_io_gpio_inst_GPIO18 (<connected-to-hps_io_hps_io_gpio_inst_GPIO18>), //                      .hps_io_gpio_inst_GPIO18
		.hps_io_hps_io_gpio_inst_GPIO19 (<connected-to-hps_io_hps_io_gpio_inst_GPIO19>), //                      .hps_io_gpio_inst_GPIO19
		.hps_io_hps_io_gpio_inst_GPIO22 (<connected-to-hps_io_hps_io_gpio_inst_GPIO22>), //                      .hps_io_gpio_inst_GPIO22
		.hps_io_hps_io_gpio_inst_GPIO23 (<connected-to-hps_io_hps_io_gpio_inst_GPIO23>), //                      .hps_io_gpio_inst_GPIO23
		.hps_io_hps_io_gpio_inst_GPIO24 (<connected-to-hps_io_hps_io_gpio_inst_GPIO24>), //                      .hps_io_gpio_inst_GPIO24
		.hps_io_hps_io_gpio_inst_GPIO25 (<connected-to-hps_io_hps_io_gpio_inst_GPIO25>), //                      .hps_io_gpio_inst_GPIO25
		.hps_io_hps_io_gpio_inst_GPIO26 (<connected-to-hps_io_hps_io_gpio_inst_GPIO26>), //                      .hps_io_gpio_inst_GPIO26
		.hps_io_hps_io_gpio_inst_GPIO27 (<connected-to-hps_io_hps_io_gpio_inst_GPIO27>), //                      .hps_io_gpio_inst_GPIO27
		.hps_io_hps_io_gpio_inst_GPIO28 (<connected-to-hps_io_hps_io_gpio_inst_GPIO28>), //                      .hps_io_gpio_inst_GPIO28
		.hps_io_hps_io_gpio_inst_GPIO29 (<connected-to-hps_io_hps_io_gpio_inst_GPIO29>), //                      .hps_io_gpio_inst_GPIO29
		.hps_io_hps_io_gpio_inst_GPIO30 (<connected-to-hps_io_hps_io_gpio_inst_GPIO30>), //                      .hps_io_gpio_inst_GPIO30
		.hps_io_hps_io_gpio_inst_GPIO31 (<connected-to-hps_io_hps_io_gpio_inst_GPIO31>), //                      .hps_io_gpio_inst_GPIO31
		.hps_io_hps_io_gpio_inst_GPIO32 (<connected-to-hps_io_hps_io_gpio_inst_GPIO32>), //                      .hps_io_gpio_inst_GPIO32
		.hps_io_hps_io_gpio_inst_GPIO33 (<connected-to-hps_io_hps_io_gpio_inst_GPIO33>), //                      .hps_io_gpio_inst_GPIO33
		.hps_io_hps_io_gpio_inst_GPIO34 (<connected-to-hps_io_hps_io_gpio_inst_GPIO34>), //                      .hps_io_gpio_inst_GPIO34
		.hps_io_hps_io_gpio_inst_GPIO37 (<connected-to-hps_io_hps_io_gpio_inst_GPIO37>), //                      .hps_io_gpio_inst_GPIO37
		.hps_io_hps_io_gpio_inst_GPIO44 (<connected-to-hps_io_hps_io_gpio_inst_GPIO44>), //                      .hps_io_gpio_inst_GPIO44
		.hps_io_hps_io_gpio_inst_GPIO48 (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>), //                      .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53 (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>), //                      .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54 (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>), //                      .hps_io_gpio_inst_GPIO54
		.memory_mem_a                   (<connected-to-memory_mem_a>),                   //                memory.mem_a
		.memory_mem_ba                  (<connected-to-memory_mem_ba>),                  //                      .mem_ba
		.memory_mem_ck                  (<connected-to-memory_mem_ck>),                  //                      .mem_ck
		.memory_mem_ck_n                (<connected-to-memory_mem_ck_n>),                //                      .mem_ck_n
		.memory_mem_cke                 (<connected-to-memory_mem_cke>),                 //                      .mem_cke
		.memory_mem_cs_n                (<connected-to-memory_mem_cs_n>),                //                      .mem_cs_n
		.memory_mem_ras_n               (<connected-to-memory_mem_ras_n>),               //                      .mem_ras_n
		.memory_mem_cas_n               (<connected-to-memory_mem_cas_n>),               //                      .mem_cas_n
		.memory_mem_we_n                (<connected-to-memory_mem_we_n>),                //                      .mem_we_n
		.memory_mem_reset_n             (<connected-to-memory_mem_reset_n>),             //                      .mem_reset_n
		.memory_mem_dq                  (<connected-to-memory_mem_dq>),                  //                      .mem_dq
		.memory_mem_dqs                 (<connected-to-memory_mem_dqs>),                 //                      .mem_dqs
		.memory_mem_dqs_n               (<connected-to-memory_mem_dqs_n>),               //                      .mem_dqs_n
		.memory_mem_odt                 (<connected-to-memory_mem_odt>),                 //                      .mem_odt
		.memory_mem_dm                  (<connected-to-memory_mem_dm>),                  //                      .mem_dm
		.memory_oct_rzqin               (<connected-to-memory_oct_rzqin>)                //                      .oct_rzqin
	);

